# Generated by Django 3.2.25 on 2024-05-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240529_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_measurement', models.DecimalField(decimal_places=2, help_text='Size of frame per lens horizontally (in mm)', max_digits=5)),
                ('b_measurement', models.DecimalField(decimal_places=2, help_text='Size of frame per lens vertically (in mm)', max_digits=5)),
                ('bridge_measurement', models.DecimalField(decimal_places=2, help_text='Bridge measurement (in mm)', max_digits=5)),
                ('temple_length', models.PositiveIntegerField(choices=[(125, '125 mm'), (130, '130 mm'), (135, '135 mm'), (140, '140 mm'), (145, '145 mm'), (150, '150 mm'), (155, '155 mm'), (160, '160 mm'), (165, '165 mm'), (170, '170 mm'), (175, '175 mm'), (180, '180 mm'), (185, '185 mm'), (190, '190 mm'), (195, '195 mm'), (200, '200 mm'), (205, '205 mm'), (210, '210 mm'), (215, '215 mm'), (220, '220 mm'), (225, '225 mm'), (230, '230 mm'), (235, '235 mm'), (240, '240 mm'), (245, '245 mm'), (250, '250 mm')], help_text='Temple length (in mm)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frame_size', to='products.product')),
            ],
            options={
                'verbose_name': 'Frame Size',
                'verbose_name_plural': 'Frame Sizes',
            },
        ),
    ]
