# Generated by Django 3.2.25 on 2024-05-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_framesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='lens_options',
            field=models.ManyToManyField(blank=True, to='products.LensOption'),
        ),
    ]
