# Generated by Django 3.2.25 on 2024-05-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240529_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lensoption',
            old_name='color',
            new_name='colour',
        ),
    ]
