# Generated by Django 3.2.25 on 2024-05-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_color_lensoption_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lens_options',
        ),
    ]
